<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- IMPORTS -->
    <xacro:include filename="inertial_macros.xacro"/>
    
    <!-- RANDOM COLOURS FOR DEBUG PURPOSES -->
    <material name="white">
        <color rgba="1 1 1 0.3"/>
    </material>
    
    <material name="light_grey">
        <color rgba="0.9 0.9 0.9 0.4"/>
    </material>
    
    <material name="black">
        <color rgba="0.2 0.2 0.2 0.4"/>
    </material>
    
    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>
    
    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>
   
    <!-- ROOT LINK 
         the datum point/point of reference and point that
         everything ultimately connects to
    -->
    <link name="base_link"></link>
    
    <!-- base_footprint is a child but of base_link but
         has the same position as its needed for SLAM toolbox 
    -->
    <link name="base_footprint"></link>
    
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0"/>
    </joint>
    
    <!-- BODY LINKS 
         these define the body of the ESDA which is simplified
         as a series of boxes
    -->
    <!-- DRIVE BOX LINK -->
    <xacro:property name="drive_box_x" value="0.5725"/>
    <xacro:property name="drive_box_y" value="0.575"/>
    <xacro:property name="drive_box_z" value="0.276"/>
    <xacro:property name="drive_box_m" value="5"/>
    
    <link name="drive_box">
        <visual>
            <geometry>
                <box size="${drive_box_x} ${drive_box_y} ${drive_box_z}" />
            </geometry>
            <material name="white"/>
        </visual>
        
        <collision>
            <geometry>
                <box size="${drive_box_x} ${drive_box_y} ${drive_box_z}" />
            </geometry>
            <material name="white"/>
        </collision>   
        
        <xacro:inertial_box mass="${drive_box_m}" x="${drive_box_x}" y="${drive_box_y}" z="${drive_box_z}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    
    <joint name="drive_box_joint" type="fixed">
        <parent link="base_link"/>
        <child link="drive_box"/>
        <origin xyz="-${drive_box_x/2} 0 0"/>
    </joint>
    
    <!-- STEERING BOX LINK -->
    <xacro:property name="steer_box_x" value="0.378"/>
    <xacro:property name="steer_box_y" value="0.575"/>
    <xacro:property name="steer_box_z" value="0.146"/>
    <xacro:property name="steer_box_m" value="5"/>
    
    <link name="steering_box">
        <visual>
            <geometry>
                <box size="${steer_box_x} ${steer_box_y} ${steer_box_z}" />
            </geometry>
            <material name="white"/>
        </visual>
        
        <collision>
            <geometry>
                <box size="${steer_box_x} ${steer_box_y} ${steer_box_z}" />
            </geometry>
            <material name="white"/>
        </collision>       
        
        <xacro:inertial_box mass="${steer_box_m}" x="${steer_box_x}" y="${steer_box_y}" z="${steer_box_z}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box> 
    </link>
    
    <joint name="steering_box_joint" type="fixed">
        <parent link="base_link"/>
        <child link="steering_box"/>
        <origin xyz="${steer_box_x/2} 0 -${drive_box_z/2-steer_box_z/2}"/> <!-- -0.065 -->
    </joint>
    
    <!-- WHEEL LINKS
         these define the 4 wheels and their attachment to 
         the vehicle. Note due to complexity of CAD, wheels are
         parallel and upright as they don't need accurate modelling
    -->
    <xacro:property name="wheel_rad" value="0.1325"/>
    <xacro:property name="wheel_len" value="0.07"/>
    <xacro:property name="wheel_mass" value="2"/>
    
    <!-- DRIVE WHEELS -->
    <xacro:property name="drive_wheel_x_off" value="0.38724"/>
    <xacro:property name="drive_wheel_y_off" value="0.48166"/>
    <xacro:property name="drive_wheel_z_off" value="0.22"/>
    
    <link name="right_drive_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_len}"/>
            </geometry>
            <material name="black"/>
        </visual>
        
        <collision>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_len}"/>
            </geometry>
            <material name="black"/>
        </collision>
        
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_rad}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <joint name="right_drive_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_drive_wheel"/>
        <origin xyz="-${drive_wheel_x_off} -${drive_wheel_y_off} -${drive_wheel_z_off}" rpy="${pi/2} 0 0 "/>
        <axis xyz="0 0 1"/>
    </joint>
    
    <link name="left_drive_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_len}"/>
            </geometry>
            <material name="black"/>
        </visual>
        
        <collision>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_len}"/>
            </geometry>
            <material name="black"/>
        </collision>
        
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_rad}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <joint name="left_drive_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_drive_wheel"/>
        <origin xyz="-${drive_wheel_x_off} ${drive_wheel_y_off} -${drive_wheel_z_off}" rpy="-${pi/2} 0 0 "/>
        <axis xyz="0 0 -1"/>
    </joint>
 
   <!-- STEERING WHEELS -->
    <xacro:property name="steer_wheel_x_off" value="0.235"/>
    <xacro:property name="steer_wheel_y_off" value="0.52297"/>
    <xacro:property name="steer_wheel_z_off" value="0.208"/>
    
    <link name="right_steering_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_len}"/>
            </geometry>
            <material name="light_grey"/>
        </visual>
        
        <collision>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_len}"/>
            </geometry>
            <material name="light_grey"/>
        </collision>
        
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_rad}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <joint name="right_steering_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_steering_wheel"/>
        <origin xyz="${steer_wheel_x_off} -${steer_wheel_y_off} -${steer_wheel_z_off}" rpy="${pi/2} 0 0 "/>
        <axis xyz="0 0 1"/>
    </joint>
    
    <link name="left_steering_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_len}"/>
            </geometry>
            <material name="light_grey"/>
        </visual>
        
        <collision>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_len}"/>
            </geometry>
            <material name="light_grey"/>
        </collision>
        
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_rad}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <joint name="left_steering_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_steering_wheel"/>
        <origin xyz="${steer_wheel_x_off} ${steer_wheel_y_off} -${steer_wheel_z_off}" rpy="-${pi/2} 0 0 "/>
        <axis xyz="0 0 -1"/>
    </joint>
    
    <link name="mid_steering_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_len}"/>
            </geometry>
            <material name="light_grey"/>
        </visual>
        
        <collision>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_len}"/>
            </geometry>
            <material name="light_grey"/>
        </collision>
        
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_rad}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <joint name="mid_steering_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="mid_steering_wheel"/>
        <origin xyz="${steer_wheel_x_off} 0 -${steer_wheel_z_off}" rpy="-${pi/2} 0 0 "/>
        <axis xyz="0 0 -1"/>
    </joint>
    

    <!-- Adding colours to wheels for gazebo -->
    <gazebo reference="left_drive_wheel">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="right_drive_wheel">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="left_steering_wheel">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="right_steering_wheel">
        <material>Gazebo/Black</material>
    </gazebo>
</robot>
