<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- ROOT LINK 
         the datum point/point of reference and point that
         everything ultimately connects to
    -->
    <link name="base_link"></link>
    
    <!-- base_footprint is a child but of base_link but
         has the same position as its needed for SLAM toolbox 
    -->
    <link name="base_footprint"></link>
    
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0"/>
    </joint>
    
    <!-- BODY LINKS 
         these define the body of the ESDA which is simplified
         as a series of boxes
    -->
    <!-- DRIVE BOX LINK -->
    <xacro:property name="drive_box_x" value="0.5725"/>
    <xacro:property name="drive_box_y" value="0.575"/>
    <xacro:property name="drive_box_z" value="0.276"/>
    <xacro:property name="drive_box_m" value="35"/>
    
    <link name="drive_box">
        <visual>
            <geometry>
                <box size="${drive_box_x} ${drive_box_y} ${drive_box_z}" />
            </geometry>
            <material name="white"/>
        </visual>
        
        <collision>
            <geometry>
                <box size="${drive_box_x} ${drive_box_y} ${drive_box_z}" />
            </geometry>
            <material name="white"/>
        </collision>   
        
        <xacro:inertial_box mass="${drive_box_m}" x="${drive_box_x}" y="${drive_box_y}" z="${drive_box_z}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    
    <joint name="drive_box_joint" type="fixed">
        <parent link="base_link"/>
        <child link="drive_box"/>
        <origin xyz="-${drive_box_x/2} 0 0"/>
    </joint>
    
    <!-- STEERING BOX LINK -->
    <xacro:property name="steer_box_x" value="0.378"/>
    <xacro:property name="steer_box_y" value="0.575"/>
    <xacro:property name="steer_box_z" value="0.146"/>
    <xacro:property name="steer_box_m" value="29"/>
    
    <link name="steering_box">
        <visual>
            <geometry>
                <box size="${steer_box_x} ${steer_box_y} ${steer_box_z}" />
            </geometry>
            <material name="white"/>
        </visual>
        
        <collision>
            <geometry>
                <box size="${steer_box_x} ${steer_box_y} ${steer_box_z}" />
            </geometry>
            <material name="white"/>
        </collision>       
        
        <xacro:inertial_box mass="${steer_box_m}" x="${steer_box_x}" y="${steer_box_y}" z="${steer_box_z}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box> 
    </link>
    
    <joint name="steering_box_joint" type="fixed">
        <parent link="base_link"/>
        <child link="steering_box"/>
        <origin xyz="${steer_box_x/2} 0 -${drive_box_z/2-steer_box_z/2}"/> <!-- -0.065 -->
    </joint>
    
    
</robot>
